"""Auto-generated summary of the ledger. Kept separate from ledger.py so the
formatting layer can be rewritten without touching the collection logic."""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as C


def _num(r, k, fmt="{:+.3f}", d=3):
    if not hasattr(r, "get") or k not in r:
        return "-"
    v = r.get(k)
    if v is None:
        return "-"
    if isinstance(v, str):
        return v
    try:
        fv = float(v)
    except (TypeError, ValueError):
        return str(v)
    if np.isnan(fv) or np.isinf(fv):
        return "-"
    return fmt.format(fv, d)


def _int(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "-"
    return f"{int(v)}"


def _pct(v, d=1):
    """Format a FRACTION as a percentage. Feeding a raw 0.56 to a '{:.0f}%'
    spec prints '1%', which is how the fill rates first came out looking like
    0% and 1%."""
    if v is None or (isinstance(v, float) and (np.isnan(v) or np.isinf(v))):
        return "-"
    return f"{float(v) * 100:+.{d}f}%"


def row_line(r) -> str:
    return (f"| {r['strategy']} | {_num(r, 'tf', '{:.0f}m', 0)} | {_int(r['trades'])} | "
            f"{_num(r, 'gross_r')} | {_num(r, 'cost_r')} | "
            f"{_num(r, 'exp_r', '{:+.4f}', 4)} | {_num(r, 'sharpe')} | "
            f"{_num(r, 'max_dd', '{:.1f}%', 1)} |")


def summarise(df: pd.DataFrame) -> str:
    o = []
    A = o.append
    A("# Experiment Ledger\n")
    A("Auto-generated by `src/ledger_report.py` from the result files. "
      "Do not edit by hand.\n")
    A(f"Rows: **{len(df)}** | experiments: "
      f"{', '.join(sorted(set(df['exp'].astype(str))))}\n")

    A("\n## Coverage\n")
    A("| exp | split | rows | strategies | timeframes |")
    A("|---|---|---|---|---|")
    g = (df.groupby(["exp", "split"])
           .agg(rows=("strategy", "size"),
                strategies=("strategy", lambda s: len(set(s))),
                tfs=("tf", lambda s: ", ".join(
                    str(int(v)) for v in sorted(set(s.dropna())))))
           .reset_index())
    for _, r in g.iterrows():
        A(f"| {r['exp']} | {r['split']} | {int(r['rows'])} | "
          f"{int(r['strategies'])} | {r['tfs'] or '-'} |")

    A("\n## Best out-of-sample per experiment\n")
    A("Ranked by `exp_r` = gross_r - cost_r. `full` rows are whole-history "
      "runs and are optimistic; `oos`/`test` are the honest ones.\n")
    oos = df[df["split"].isin(["oos", "test", "full"])].copy()
    oos["exp_r"] = pd.to_numeric(oos["exp_r"], errors="coerce")
    oos = oos.dropna(subset=["exp_r"])
    for exp, g in oos.groupby("exp"):
        g = g.sort_values("exp_r", ascending=False)
        n_pos = int((g["exp_r"] > 0).sum())
        A(f"\n**Exp {exp}** — {n_pos}/{len(g)} rows with positive `exp_r`\n")
        A("| strategy | tf | trades | gross_r | cost_r | exp_r | sharpe | max_dd |")
        A("|---|---|---|---|---|---|---|---|")
        for _, r in g.head(6).iterrows():
            A(row_line(r))

    ci = df.dropna(subset=["ci_lo", "ci_hi", "exp_r"]).copy()
    if len(ci):
        n_excl = int((ci["ci_lo"] > 0).sum())
        A("\n## Bootstrap confidence intervals\n")
        A(f"Rows with a CI: **{len(ci)}** | intervals excluding zero: "
          f"**{n_excl}**\n")
        A("| exp | note | stop_scale | trades | exp_r | 95% CI | verdict |")
        A("|---|---|---|---|---|---|---|")
        for _, r in ci.sort_values("exp_r", ascending=False).head(18).iterrows():
            verdict = "**excludes 0**" if r["ci_lo"] > 0 else "straddles 0"
            A(f"| {r['exp']} | {r.get('note', '-')} | "
              f"{_num(r, 'stop_scale', '{:.1f}', 1)} | {_int(r['trades'])} | "
              f"{r['exp_r']:+.4f} | [{r['ci_lo']:+.4f}, {r['ci_hi']:+.4f}] | "
              f"{verdict} |")

    A("\n## Effect of stop width (exp 004, taker, whole history)\n")
    cl = df[(df["exp"].astype(str) == "004") & (df["split"] == "full")]
    if len(cl) and "note" in cl:
        tk = cl[cl["note"] == "taker (real)"]
        if len(tk):
            p = tk.pivot_table(index=["strategy", "tf"], columns="sm",
                               values="cost_r")
            q = tk.pivot_table(index=["strategy", "tf"], columns="sm",
                               values="exp_r")
            A("| config | " + " | ".join(f"{m:g}x" for m in p.columns) + " |")
            A("|---" * (len(p.columns) + 1) + "|")
            for idx, row in p.iterrows():
                A(f"| {idx[0]} {int(idx[1])}m **cost_r** | " +
                  " | ".join(f"{v:.3f}" for v in row) + " |")
            for idx, row in q.iterrows():
                A(f"| {idx[0]} {int(idx[1])}m exp_r | " +
                  " | ".join(f"{v:+.3f}" for v in row) + " |")

    if "stop_scale" not in df.columns:
        df["stop_scale"] = np.nan
    if "fill_rate" not in df.columns:
        df["fill_rate"] = np.nan
    if "note" not in df.columns:
        df["note"] = ""
    mk = df[df["exp"].astype(str) == "008"].copy()
    if len(mk):
        A("\n## Effect of execution mode (exp 008, walk-forward, 15m)\n")
        A("| stop_scale | mode | fill% | trades | gross_r | cost_r | exp_r | CAGR |")
        A("|---|---|---|---|---|---|---|---|")
        mk = mk.sort_values(["stop_scale", "exp_r"], ascending=[True, False])
        for _, r in mk.iterrows():
            A(f"| {r['stop_scale']:.1f} | {r['note']} | "
              f"{_pct(r['fill_rate'], 0)} | {_int(r['trades'])} | "
              f"{_num(r, 'gross_r')} | {_num(r, 'cost_r')} | "
              f"{_num(r, 'exp_r', '{:+.4f}', 4)} | "
              f"{_pct(r['cagr'], 1)} |")

    if "hold_hours" in df.columns:
        hp = df[(df["exp"].astype(str) == "009")].copy()
        if len(hp):
            A("\n## Effect of holding period (exp 009, 5m, post-only)\n")
            A("| tf | stop_scale | hold | trades | avg_bars held | gross_r | cost_r | exp_r | 95% CI |")
            A("|---|---|---|---|---|---|---|---|---|")
            hp = hp.sort_values(["tf", "stop_scale", "hold_hours"])
            for _, r in hp.iterrows():
                A(f"| {int(r['tf'])}m | {r['stop_scale']:.1f} | "
                  f"{_num(r, 'hold_hours', '{:.0f}h', 0)} | {_int(r['trades'])} | "
                  f"{_num(r, 'avg_bars', '{:.0f}', 0)} | {_num(r, 'gross_r')} | "
                  f"{_num(r, 'cost_r')} | {_num(r, 'exp_r', '{:+.4f}', 4)} | "
                  f"[{r['ci_lo']:+.3f}, {r['ci_hi']:+.3f}] |")
    return "\n".join(o)


if __name__ == "__main__":
    p = C.RESULTS / "ledger.csv"
    if not p.exists():
        raise SystemExit("run src/ledger.py first")
    d = pd.read_csv(p)
    out = C.JOURNAL / "ledger.md"
    out.write_text(summarise(d), encoding="utf-8")
    print(f"wrote {out}")
